# Generated by Django 4.2 on 2023-09-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_lab_principle_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='apollo_url',
            field=models.URLField(null=True),
        ),
    ]
