# Generated by Django 4.2 on 2023-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_genome_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='_metadata',
        ),
        migrations.RemoveField(
            model_name='track',
            name='_metadata',
        ),
        migrations.AddField(
            model_name='genome',
            name='_metadata_yaml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='ncbi_bioproject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
