# Generated by Django 4.2 on 2023-12-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_remove_genome__metadata_remove_track__metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genome',
            old_name='description',
            new_name='description_html',
        ),
    ]
