# Generated by Django 4.2 on 2023-12-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0015_track_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
