# Generated by Django 4.2 on 2024-02-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('notice_class', models.CharField(choices=[('info', 'info'), ('warning', 'warning')], default='', help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            A style class to set a color scheme for the notice - uses\n            <a\n                href='https://getbootstrap.com/docs/5.0/components/alerts/'\n                target='_blank'\n            >standard bootstrap styling</a>\n            (<em>info</em>: blue, <em>warning</em>: orange).\n        </li>\n    </ul>\n    ", max_length=16)),
                ('title_html', models.CharField(blank=True, help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            This will be displayed on the landing page (200 char max) as plain\n            text or inline HTML (e.g.\n            <code>&lt;em&gt;</code>,\n            <code>&lt;b&gt;</code>\n            tags).\n        </li>\n        <li style='list-style: disc;'>\n            No <code>&lt;a&gt;</code> tags please, as this creates a confusing\n            user experience (link within link).\n        </li>\n        <li style='list-style: disc;'>\n            This will be shown as a single line of text above the navbar,\n            <b>which will be cut off if too long</b>,\n            especially on small screens! Please check the length is reasonable\n            before publishing the notice.\n        </li>\n    </ul>\n    ", max_length=150, null=True)),
                ('body_markdown', models.CharField(blank=True, help_text='\n    <ul style=\'margin-left: 2rem;\'>\n        <li style=\'list-style: disc;\'>\n            Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead. HTML is also fine.\n    \n        </li>\n        <li style=\'list-style: disc;\'>\n            <b>This text will be displayed on a dedicated webpage</b>\n            that is linked to from the landing page notice.\n            If this field is left blank, there will be no link.\n        </li>\n    </ul>\n    ', max_length=10000, null=True)),
                ('material_icon', models.CharField(blank=True, help_text='\n    Optional. A valid Material Design icon ID to be displayed with the title\n    (e.g. <em>check_box</em>).\n    <a href="https://fonts.google.com/icons" target="_blank">\n    Browse 2500+ icons here\n    </a>.\n    ', max_length=50, null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Display on the portal landing page.')),
                ('is_published', models.BooleanField(default=False, help_text='Unpublished content is visible to admin users only. Use this to review content before release to public users.')),
            ],
        ),
    ]
