# Generated by Django 4.2.24 on 2025-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Plain text only please.', max_length=200)),
                ('answer', models.CharField(help_text='Plain text or HTML are accepted.', max_length=2000)),
                ('hide', models.BooleanField(default=False, help_text="Don't show this entry on the FAQs page.")),
            ],
        ),
    ]
