# Generated by Django 4.2.24 on 2025-09-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_populate_faqs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='hide',
            new_name='hidden',
        ),
    ]
