# Generated by Django 4.2 on 2023-12-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('genomes', '0008_alter_genome_accession_id_alter_genome_apollo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
