# Generated by Django 4.2 on 2023-09-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='genomes'),
        ),
    ]
