# Generated by Django 4.2 on 2023-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0002_alter_genome_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='apollo_url',
            field=models.URLField(null=True),
        ),
    ]
