# Generated by Django 4.2 on 2023-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0004_alter_genome__metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='description_html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='image',
            field=models.ImageField(null=True, upload_to='labs'),
        ),
        migrations.AddField(
            model_name='lab',
            name='website_url',
            field=models.URLField(null=True),
        ),
    ]
