# Generated by Django 4.2 on 2023-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0011_rename_description_genome_description_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='ncbi_bioproject',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
