name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DJANGO_SECRET_KEY: secret
  HOSTNAME: 127.0.0.1:5000
  DB_NAME: apollo_portal
  DB_USER: apollo_portal
  DB_PASSWORD: secret
  MAIL_FROM_ADDRESS: apollo-support@genome.edu.au
  MAIL_TO_ADDRESS: help@genome.edu.au
  MAIL_USE_TLS: true
  MAIL_HOSTNAME: smtp.mailtrap.io
  MAIL_SMTP_PORT: 2525
  MAIL_SMTP_USERNAME: ""
  MAIL_SMTP_PASSWORD: ""
  RECAPTCHA_SITE_KEY: ""
  RECAPTCHA_SECRET_KEY: ""

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd apollo_portal && python manage.py test
